### ISSUE TITLE
When an existing factor_type is truncated, the wrong message is returned

### ISSUE THREAD

**Issue by OphelieC** [B-Souty/OktaLoginWrapper#8]
**Description**
When trying to authenticate, if an existing but truncated `factor_type` is sent, it will return a message as if you are logged in.

**Steps**
1. Open your instance
2. Send the following
`my_session.okta_auth('name', 'password', factor_type='questio' )`

**Expected behavior**
An error message is displayed.
> Cannot find this factor_type. Check spelling or assignment.

**Current behavior**
The following message is displayed:
>You are now logged in. 

**Notes**
It also works with `toke`, `tok`, `questi`...

**Comment by B-Souty** [comment]
Thank for catching this. The problem was caused by the fact that I'm using ```if ... in``` instead of ```if ... ==``` here on line 70 https://github.com/B-Souty/OktaLoginWrapper/blob/598d087bd8148e2715508a1b63b56fe90dce5681/oktaloginwrapper/OktaLoginWrapper.py#L68-L74

Because of that the script wasn't crashing because it was getting a correct factor_id  but the factor_type passed to _okta_verify() was still the truncated one. 
I added line 75 to make sure if a factor_id is found, the factor_type is updated to the one attached to this factor_id:
https://github.com/B-Souty/OktaLoginWrapper/blob/598d087bd8148e2715508a1b63b56fe90dce5681/oktaloginwrapper/OktaLoginWrapper.py#L75
